name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create application.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: Build Project
        run: ./gradlew clean build

      - name: Rename Build Artifact
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: Create Tarball
        run: tar -czvf $GITHUB_SHA.tar.gz project.jar appspec.yml scripts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://memory-server/$GITHUB_SHA.tar.gz

      - name: Create Deployment
        run: aws deploy create-deployment
          --application-name memory-server
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name Production
          --s3-location bucket=memory-server,bundleType=tgz,key=$GITHUB_SHA.tar.gz